#!/usr/bin/env bun
import { readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

/**
 * Why: the docs' header search is a real <dialog class="command"> palette
 * (the shipped component), so it needs a searchable index. Rather than
 * crawling at runtime (fetching 55 pages) or hand-maintaining a list, the
 * index is generated at build time from exactly two sources of truth that
 * already exist: the NAV array in layout.ts (pages + sections, in nav order)
 * and every doc page's <h2> headings. verify.ts regenerates this text and
 * fails the build when the committed file drifts — same pattern as snippets.
 */

const ROOT = join(import.meta.dirname, '..', '..');
const SRC = join(ROOT, 'src');
const DOCS = join(SRC, 'documentation');
const OUT = join(DOCS, 'js/search-index.js');

/** Mirrors layout.ts buildToc(): h2s without an authored id get
 * 'toc-' + slug at runtime — palette deep-links must hit the same ids the
 * SPA assigns after navigation. */
function tocId(text: string): string {
  return 'toc-' + text.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-+|-+$/g, '');
}

function decode(text: string): string {
  // \u0026 is "&" — every HTML entity here is written with the escape so the
  // sequence never appears literally in this file (editors/tools that
  // normalize entities silently turned these replaces into no-ops once).
  return text
    .replace(/\u0026#39;/g, "'")
    .replace(/\u0026quot;/g, '"')
    .replace(/\u0026lt;/g, '<')
    .replace(/\u0026gt;/g, '>')
    .replace(/\u0026amp;/g, '\u0026');
}

/** Page entries from the NAV array (labels, order, sections) — layout.ts is
 * the single source of truth for what the docs *are*. */
function navPages(): { label: string; href: string; section: string }[] {
  const layout = readFileSync(join(DOCS, 'js/layout.ts'), 'utf8');
  const pages: { label: string; href: string; section: string }[] = [];
  for (const block of layout.matchAll(/\{\s*heading:\s*'([^']+)',\s*items:\s*\[([\s\S]*?)\]\s*\}/g)) {
    const section = decode(block[1]);
    for (const item of block[2].matchAll(/label:\s*'([^']+)',\s*href:\s*'([^']+)'/g)) {
      pages.push({ label: decode(item[1]), href: item[2], section });
    }
  }
  return pages;
}

/** Section entries: every <h2> of a page's source HTML, tags/entities
 * stripped like layout.ts's getHeadingText() does at runtime. */
function pageSections(file: string): { text: string; id: string }[] {
  const html = readFileSync(file, 'utf8');
  const out: { text: string; id: string }[] = [];
  for (const m of html.matchAll(/<h2([^>]*)>([\s\S]*?)<\/h2>/g)) {
    const text = decode(m[2].replace(/<[^>]+>/g, '')).replace(/\s+/g, ' ').trim();
    if (!text) continue;
    // keep authored ids (the TOC does the same) so palette deep-links land
    const authored = m[1].match(/id="([^"]+)"/);
    out.push({ text, id: authored ? authored[1] : tocId(text) });
  }
  return out;
}

/** Build the search-index.js source text (exported so verify.ts can compare
 * the committed copy against a fresh regeneration). */
export function buildSearchIndexText(): string {
  type Entry = { t: string; h: string; s: string };
  const entries: Entry[] = [];
  for (const page of navPages()) {
    entries.push({ t: page.label, h: page.href, s: page.section });
    const file = join(DOCS, page.href);
    for (const sec of pageSections(file)) {
      entries.push({ t: sec.text, h: `${page.href}#${sec.id}`, s: page.label });
    }
  }
  return (
    '// GENERATED by scripts/lib/search-index.ts on every build (via build.ts) —\n' +
    '// do not edit by hand; dist-freshness + working-tree gates catch drift.\n' +
    '// Docs search index: t = title, h = href (page or page#section), s = group\n' +
    '// (nav section for pages, page label for sections). Under .docs — this is\n' +
    '// doc-site data, not a shipped component contract (AGENTS.md "No window globals").\n' +
    'globalThis._defussShadcn = globalThis._defussShadcn || {};\n' +
    'globalThis._defussShadcn.docs = globalThis._defussShadcn.docs || {};\n' +
    `globalThis._defussShadcn.docs.searchIndex = ${JSON.stringify(entries)};\n`
  );
}

// CLI entry: regenerate the committed index into src/ (build.ts copies it to dist/)
if (import.meta.main) {
  const files = readdirSync(DOCS).filter((f) => f.endsWith('.html'));
  const text = buildSearchIndexText();
  writeFileSync(OUT, text);
  const n = (text.match(/"t":/g) ?? []).length;
  console.log(`search-index: ${n} entries from ${files.length} pages → src/documentation/js/search-index.js`);
}
